name: Build AEology

on:
  push:
    tags:
      - "*.*.*"
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get release tag
        run: |
          echo "${GITHUB_REF##*/}" | cut -d '-' -f 2- >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.12"
          cache: pip
        
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
          
      - name: Install pyinstaller
        run: python -m pip install pyinstaller>=5.1
        
      - name: Run pyinstaller
        run: pyinstaller --onefile --icon=AEology-logo.ico ./AEology.py
        
      - name: Copy exe
        run: xcopy /y '.\dist\AEology.exe' ${GITHUB_WORKDIR}
      
      - name: Update version file
        run: |
          Remove-Item -Path LatestVersion.txt -Force
          Set-Content -Path LatestVersion.txt -Value $env:RELEASE_VERSION

      - name: Cleanup
        run: |
          rm -r -fo dist
          rm -r -fo build
          rm AEology.spec

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name = "Github Action"
          git add .
          git commit -a -m "Build AEology"
          
      - name: Push changes
        if: ${{ success() }}
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release zip
        run: Compress-Archive -Path AEology.exe, README.txt, LICENSE, AEology-config.ini -DestinationPath 'AEology-${{ env.RELEASE_VERSION }}.zip'
    
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: AEology-${{ env.RELEASE_VERSION }}.zip
          release_name: ${{ env.RELEASE_VERSION }}
          generate_release_notes: yes
